name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      QUMA_TEST_DRIVERS: sqlite,mysql,pgsql
      QUMA_DB_MYSQL_HOST: localhost
      QUMA_DB_PGSQL_HOST: localhost
      QUMA_DB_NAME: quma_db
      QUMA_DB_USER: root
      QUMA_DB_PASSWORD: root
    steps:
      - name: Setup PHP extensions
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: '8.5'
          extensions: sqlite3, pgsql, mysql, gd, pcov, curl, xml, zip
          coverage: pcov

      - name: Disable Xdebug
        run: sudo phpdismod xdebug

      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install packages with composer
        run: composer install

      - name: Start mysql server and create test db
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE `${{ env.QUMA_DB_NAME }}`;' -u${{ env.QUMA_DB_USER }} -p${{ env.QUMA_DB_PASSWORD }}

      - name: Start postgresql server and create test db
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createdb ${{ env.QUMA_DB_NAME }}
          sudo -u postgres psql -c "CREATE USER ${{ env.QUMA_DB_USER }} WITH SUPERUSER PASSWORD '${{ env.QUMA_DB_PASSWORD }}';"

      - name: Run tests
        run: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-filter=src --coverage-html=coverage

      - name: Run Psalm
        run: vendor/bin/psalm --output-format=github --shepherd

      - name: Upload coverage report to Codacy
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_ACCOUNT_TOKEN }}
          coverage-reports: coverage.xml
